// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.VoiceExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "b4558cd7-da41-47e7-8969-46c357a1b8b3";
        public const string Name = "Voice Commands";
        public const string Description = @"Control Visual Studio using your own voice and with high accuracy";
        public const string Language = "en-US";
        public const string Version = "2.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "voice, speech, speak";
    }
}
