// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.VoiceExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVoiceExtensionPkgString = "b4558cd7-da41-47e7-8969-46c357a1b8b3";
        public static Guid guidVoiceExtensionPkg = new Guid(guidVoiceExtensionPkgString);

        public const string guidVoiceExtensionCmdSetString = "9ae4e318-bbcc-41c1-a880-e64ac747659b";
        public static Guid guidVoiceExtensionCmdSet = new Guid(guidVoiceExtensionCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidMyCommand = 0x0100;
    }
}